### ISSUE TITLE
Permissions of alsatplg -o output are hardcoded to S_IRUSR | S_IWUSR (600)

### ISSUE THREAD

**Issue by marc-hb** [alsa-project/alsa-utils#126]
From https://github.com/alsa-project/alsa-utils/blob/c8c348e28a258f17e3/topology/topology.c#L172

```C
static int save(const char *output_file, void *buf, size_t size)
{

               fd = open(fname, O_RDWR | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);

```

When using alsatplg in a build system (e.g.: https://github.com/thesofproject/sof/blob/3e1c160e5053eae/tools/topology/topology1/CMakeLists.txt#L243), all other artefacts follow the process's umask **except** alsatplg output. This causes subtle and time-consuming errors when trying to share artefacts across different processes.

git blame finds: 

commit cbabe7a3f0cc84ecd352d4cbf85148946fa6c0d5
Author: Jaroslav Kysela <perex@perex.cz>
Date:   Thu Dec 19 15:36:05 2019 +0100

    alsatplg: rewrite to use the new libatopology functions

Before cbabe7a3f0, opening the output file was delegated to library function `snd_tplg_build_file()`. Not sure what permissions were used then.

Workaround:
```shell
alsatplg -c intput.conf -o - > output.tplg
```

**Comment by perexg** [comment]
Thank you for your report. It's fixed now in https://github.com/alsa-project/alsa-utils/commit/8e71fba810b87c48600191f4e2e13d0e351f73bc. The problem was in the original code in alsa-lib, too. Several Intel people touched the code and the result ends with this too restrictive permission settings.

- https://github.com/alsa-project/alsa-lib/commit/5b518c915#diff-380e8c90a71ab889257ac12231df110b4a6993eefc83c19368f192419c33ae3cL273
- https://github.com/alsa-project/alsa-lib/commit/37692bb98#diff-380e8c90a71ab889257ac12231df110b4a6993eefc

**Comment by marc-hb** [comment]
Thanks @perexg for the super quick fix.

> Several Intel people touched the code and the result ends with this too restrictive permission settings.

`git blame` can be cruel :-) Looks like that change was trying to remove spurious exec permissions and went too far. Hard to tell for sure because it's just one line drown in a much bigger commit.
